### ISSUE TITLE
关于 PyTorch 依赖版本的咨询

### ISSUE THREAD

**Issue by zhabuye** [DeepLink-org/dlinfer#119]
您好， @jinminxi104 
我注意到在0.1.1及之后的版本中，对 PyTorch 的依赖要求从 2.1.0 提升到了 2.3.1。我当前的环境中使用的是 PyTorch 2.1.0，并且希望能够继续使用这个版本运行贵库的最新版本。

对此我想咨询以下几个问题：

请问是什么原因促使您决定将 PyTorch 的依赖版本提升到 2.3.1？是否有特定的功能或改进在 2.3.1 中引入，这些是 2.1.0 版本所不支持的？如果有，这些功能是否提供了向后兼容的解决方案，以便在旧版本 PyTorch 上也能使用？

感谢您的帮助并期待您的回复。

**Comment by tangzhiyi11** [comment]
感谢您的关注和使用。

> 请问是什么原因促使您决定将 PyTorch 的依赖版本提升到 2.3.1？

升级到 2.3.1 主要是因为 华为图模式使用了 torch.compile。torch.compile 是 pytorch 2.0 后引入的新功能，是个快速迭代和bug修复的模块。升高 pytorch 版本，会带来更稳定更优的 torch.compile。如果主要使用图模式，还是建议升级到 2.3.1 版本，未来可能还会尽可能升到最新的 pytorch 版本。

> 如果有，这些功能是否提供了向后兼容的解决方案，以便在旧版本 PyTorch 上也能使用？

如果主要使用 eager 模式，2.1 版本应该就够了。如果 2.1 版本的 eager 模式使用上有什么问题，欢迎给我们反馈，我们会进一步查看解决。

**Comment by zhabuye** [comment]
感谢您的回复！！！
